{
  [SFX_COIN_DROP] = {{
    .type = RIV_WAVEFORM_NOISE,
    .delay = 0,
    .attack = 0.025, .decay = 0.075, .sustain = 0.075, .release = 0.075,
    .start_frequency = 2*1760.0, .end_frequency = 2*1760.0,
    .amplitude = 0.15, .sustain_level = 0.1,
    .duty_cycle = 0.5, .pan = 0,
  }},
  [SFX_COIN_PICKUP] = {{
    .type = RIV_WAVEFORM_TRIANGLE,
    .delay = 0,
    .attack = 0.025, .decay = 0.075, .sustain = 0.075, .release = 0.075,
    .start_frequency = 1760.0, .end_frequency = 1760.0,
    .amplitude = 0.25, .sustain_level = 0.1,
    .duty_cycle = 0.5, .pan = 0,
  }},
  [SFX_DASH] = {{
    .type = RIV_WAVEFORM_NOISE,
    .attack = 0.025, .decay = 0.1, .sustain = 0.2, .release = 0.1,
    .start_frequency = 700, .end_frequency = 40,
    .amplitude = 0.10, .sustain_level = 0.15,
    .duty_cycle = 0.5, .pan = 0.0,
  }},
  [SFX_ATTACK] = {
    {
      .type = RIV_WAVEFORM_SINE,
      .attack = 0.05, .decay = 0.0, .sustain = 0.0, .release = 0.04,
      .start_frequency = 2000, .end_frequency = 100,
      .amplitude = 0.15, .sustain_level = 0.0,
      .duty_cycle = 0.5, .pan = 0.33,
    },{
      .type = RIV_WAVEFORM_NOISE,
      .attack = 0.05, .decay = 0.0, .sustain = 0.0, .release = 0.025,
      .start_frequency = 1500, .end_frequency = 10,
      .amplitude = 0.10, .sustain_level = 0.0,
      .duty_cycle = 0.2, .pan = -0.33,
    }
  },
  [SFX_HURT_MONSTER] = {{
    .id = 1,
    .type = RIV_WAVEFORM_NOISE,
    .delay = 0,
    .attack = 0.01, .decay = 0.025, .sustain = 0.025, .release = 0.015,
    .start_frequency = 440.0, .end_frequency = 220.0,
    .amplitude = 0.25, .sustain_level = 0.25,
    .duty_cycle = 0.15, .pan = 0,
  }},
  [SFX_HURT_PLAYER] = {{
    .id = 2,
    .type = RIV_WAVEFORM_NOISE,
    .delay = 0,
    .attack = 0.01, .decay = 0.025, .sustain = 0.025, .release = 0.015,
    .start_frequency = 330.0, .end_frequency = 110.0,
    .amplitude = 0.25, .sustain_level = 0.25,
    .duty_cycle = 0.15, .pan = 0,
  }},
  [SFX_DIE_MONSTER] = {{
    .id = 3,
    .type = RIV_WAVEFORM_NOISE,
    .attack = 0.025, .decay = 0.075, .sustain = 0.05, .release = 0.4,
    .start_frequency = 100, .end_frequency = 22,
    .amplitude = 0.15, .sustain_level = 0.5,
    .duty_cycle = 0.5, .pan = 0.0,
  }},
  [SFX_DIE_PLAYER] = {{
    .type = RIV_WAVEFORM_PULSE,
    .attack = 0.025, .decay = 0.075, .sustain = 0.15, .release = 0.5,
    .start_frequency = 90, .end_frequency = 22,
    .amplitude = 0.3, .sustain_level = 0.5,
    .duty_cycle = 0.5, .pan = 0.0,
  }},
  [SFX_OPEN_DOOR] = {
    {
      .type = RIV_WAVEFORM_NOISE,
      .attack = 0.2, .decay = 0.2, .sustain = 0.15, .release = 0.25,
      .start_frequency = 100, .end_frequency = 330,
      .amplitude = 0.25, .sustain_level = 0.2,
      .duty_cycle = 0.5, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_NOISE, .delay = 0.65,
      .attack = 0.025, .decay = 0.025, .sustain = 0.025, .release = 0.20,
      .start_frequency = 140, .end_frequency = 30,
      .amplitude = 0.25, .sustain_level = 0.5,
      .duty_cycle = 0.5, .pan = 0.0,
    },
  },
  [SFX_KEY_PICKUP] = {
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.125,
      .attack = 0.150, .decay = 0.05, .sustain = 0.5, .release = 0.1,
      .start_frequency = RIV_NOTE_C5, .end_frequency = RIV_NOTE_C5,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.25,
      .attack = 0.150, .decay = 0.05, .sustain = 0.5, .release = 0.1,
      .start_frequency = RIV_NOTE_F5, .end_frequency = RIV_NOTE_F5,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.375,
      .attack = 0.150, .decay = 0.05, .sustain = 0.5, .release = 0.1,
      .start_frequency = RIV_NOTE_A5, .end_frequency = RIV_NOTE_A5,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.5,
      .attack = 0.150, .decay = 0.05, .sustain = 0.5, .release = 0.1,
      .start_frequency = RIV_NOTE_C6, .end_frequency = RIV_NOTE_C6,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
  },
  [SFX_CHEST_OPEN] = {
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.125,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 0.5,
      .start_frequency = RIV_NOTE_C4, .end_frequency = RIV_NOTE_C4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.5,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 0.5,
      .start_frequency = RIV_NOTE_G4, .end_frequency = RIV_NOTE_G4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
  },
  [SFX_POTION_PICKUP] = {{
    .type = RIV_WAVEFORM_SINE,
    .attack = 0.15, .decay = 0.2, .sustain = 0.2, .release = 0.1,
    .start_frequency = 110, .end_frequency = 880,
    .amplitude = 0.2, .sustain_level = 0.25,
    .duty_cycle = 0.5, .pan = 0.0,
  }},
  [SFX_UPGRADE] = {
    {
      .type = RIV_WAVEFORM_PULSE,
      .attack = 0.025, .decay = 0.2, .sustain = 0.3, .release = 0.25,
      .start_frequency = 55, .end_frequency = 1760,
      .amplitude = 0.25, .sustain_level = 0.25,
      .duty_cycle = 0.1, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_PULSE,
      .attack = 0.025, .decay = 0.2, .sustain = 0.3, .release = 0.25,
      .start_frequency = 55, .end_frequency = 1760/2,
      .amplitude = 0.25, .sustain_level = 0.25,
      .duty_cycle = 0.1, .pan = 0.0,
    },
  },
  [SFX_EXPLOSION] = {
    {
      .type = RIV_WAVEFORM_NOISE,
      .attack = 0.025, .decay = 0.2, .sustain = 0.2, .release = 0.3,
      .start_frequency = 160, .end_frequency = 30,
      .amplitude = 0.25, .sustain_level = 0.3,
      .duty_cycle = 0.5, .pan = -0.5,
    },
    {
      .type = RIV_WAVEFORM_NOISE, .delay = 0.01,
      .attack = 0.025, .decay = 0.2, .sustain = 0.2, .release = 0.3,
      .start_frequency = 50, .end_frequency = 30,
      .amplitude = 0.25, .sustain_level = 0.3,
      .duty_cycle = 0.5, .pan = 0.5,
    },
  },
  [SFX_GAME_COMPLETE1] = {
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.0,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 0.25,
      .start_frequency = RIV_NOTE_C4, .end_frequency = RIV_NOTE_C4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.125,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 0.5,
      .start_frequency = RIV_NOTE_E4, .end_frequency = RIV_NOTE_E4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=0.25,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 0.5,
      .start_frequency = RIV_NOTE_A4, .end_frequency = RIV_NOTE_A4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
  },
  [SFX_GAME_COMPLETE2] = {
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=1,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 0.25,
      .start_frequency = RIV_NOTE_D4, .end_frequency = RIV_NOTE_D4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=1+0.125,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 0.5,
      .start_frequency = RIV_NOTE_F4, .end_frequency = RIV_NOTE_F4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=1+0.25,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 0.5,
      .start_frequency = RIV_NOTE_B4, .end_frequency = RIV_NOTE_B4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
  },
  [SFX_GAME_COMPLETE3] = {
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=2,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 1,
      .start_frequency = RIV_NOTE_E4, .end_frequency = RIV_NOTE_E4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=2+0.125,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 1,
      .start_frequency = RIV_NOTE_G4, .end_frequency = RIV_NOTE_G4,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
    {
      .type = RIV_WAVEFORM_TRIANGLE, .delay=2+0.25,
      .attack = 0.050, .decay = 0.3, .sustain = 0.5, .release = 1,
      .start_frequency = RIV_NOTE_C5, .end_frequency = RIV_NOTE_C5,
      .amplitude = 0.2, .sustain_level = 0.3,
      .duty_cycle = 0.2, .pan = 0.0,
    },
  },
};
